version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: q2Teste
    ports:
      - "15432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./src/cmd:/docker-entrypoint-initdb.d